---
production:
  
  # Allows us to reference this using "production" or a short alias, "prod".
  aliases:
    - prod

  # Enable continuous delivery for this environment.
  continuous_delivery:
    # You can specify any git "ref" (tag, branch, etc) to auto deploy when
    # pushed to.
    ref: refs/heads/master

    # If you want to only deploy when a set of GitHub commit statuses are
    # passing, you can configure those here. If none are provided, SlashDeploy
    # will deploy when new commits are pushed to the git ref.
    # required_contexts:
    #  - ci/circleci
